<?php

namespace BibliothequeBundle\Repository;

/**
 * dommaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dommaineRepository extends \Doctrine\ORM\EntityRepository
{
}
