<?php

namespace BibliothequeBundle\Repository;

/**
 * empruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class empruntRepository extends \Doctrine\ORM\EntityRepository
{
}
