cite_homepage:
    path:     /accueil
    defaults: { _controller: CiteDeCultureBundle:Default:index }
cite_backpage:
    path:     /administration
    defaults: { _controller: CiteDeCultureBundle:Default:back }

