art_classique:
    resource: "@ArtClassiqueBundle/Resources/config/routing.yml"
    prefix:   /

foire:
    resource: "@FoireBundle/Resources/config/routing.yml"
    prefix:   /


citedeculture:
    resource: "@CiteDeCultureBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


