groupe_index:
    path:     /
    defaults: { _controller: "ArtClassiqueBundle:GroupeArtistes:index" }
    methods:  GET

groupe_show:
    path:     /{id}/show
    defaults: { _controller: "ArtClassiqueBundle:GroupeArtistes:show" }
    methods:  GET

groupe_new:
    path:     /new
    defaults: { _controller: "ArtClassiqueBundle:GroupeArtistes:new" }
    methods:  [GET, POST]

groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "ArtClassiqueBundle:GroupeArtistes:edit" }
    methods:  [GET, POST]

groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "ArtClassiqueBundle:GroupeArtistes:delete" }
    methods:  DELETE
