auteur_index:
    path:     /
    defaults: { _controller: "BibliothequeBundle:auteur:index" }
    methods:  GET

auteur_show:
    path:     /{id}/show
    defaults: { _controller: "BibliothequeBundle:auteur:show" }
    methods:  GET

auteur_new:
    path:     /new
    defaults: { _controller: "BibliothequeBundle:auteur:new" }
    methods:  [GET, POST]

auteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "BibliothequeBundle:auteur:edit" }
    methods:  [GET, POST]

auteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "BibliothequeBundle:auteur:delete" }
    methods:  DELETE
