emprunt_index:
    path:     /
    defaults: { _controller: "BibliothequeBundle:emprunt:index" }
    methods:  GET

emprunt_show:
    path:     /{id}/show
    defaults: { _controller: "BibliothequeBundle:emprunt:show" }
    methods:  GET

emprunt_new:
    path:     /new
    defaults: { _controller: "BibliothequeBundle:emprunt:new" }
    methods:  [GET, POST]

emprunt_edit:
    path:     /{id}/edit
    defaults: { _controller: "BibliothequeBundle:emprunt:edit" }
    methods:  [GET, POST]

emprunt_delete:
    path:     /{id}/delete
    defaults: { _controller: "BibliothequeBundle:emprunt:delete" }
    methods:  DELETE
